### ISSUE TITLE
Todo List 

### ISSUE THREAD

**Issue by listentothefrog** [listentothefrog/2Hearts#2]
- [ ] Landing page for 2Hearts
- [x] Sign in user with email and password
- [x] Sign up user with email and password
   - [ ] Verifying user when they created an account (to avoid spam accounts and will display check mark icon in the profile) 
   - [ ] Account set component
   - [ ] Saving account information in firestore
- [ ] Security rules for firestore 
- [ ] Able to add up to 6 images of the user
- [ ] Displaying people on the page
- [ ] Recommenced section for people
- [ ] Swipin on users
- [ ] Adding stories to profiles
- [ ] Reporting users 
- [ ] Send emails if someone forgot their password
- [ ] Mobile app 

# How can I help 
* triage issues
  * pick a bug, recreate it locally, then fix it
* match design on figma on existing pages if you notice an inconsistency between figma and the website you can make a pr to fix it
* we will be releasing new components that you can build

Ask me before starting and tell me the problem you are trying to solve with this feature (also make sure at least one other person besides yourself has experienced this problem).
